version: "3.9"
services:
    db:
        container_name: mydb
        image: mysql:5.7
        ports:
            - "32001:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./db:/docker-entrypoint-initdb.d/
        healthcheck:
            test: out=$$(mysqladmin ping -h localhost -P 3306 -u root --password=root 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }
            timeout: 20s
            retries: 5
        networks:
            - my-network
    db-filler:
        container_name: db-filler
        links:
            - "db"
        build: db-filler/
        ports:
            - "5001:5000"
        volumes:
            - ./db-filler:/db-filler
        depends_on:
            db:
                condition: service_healthy
        networks:
            - my-network
    app:
        build: ./app 
        links: 
            - db 
        ports:
            - "8000:8000"
        depends_on:
            db:
                condition: service_healthy
        networks:
            - my-network
networks:
    my-network:
        driver: bridge
